import Navbar from '@/components/navbar/Navbar'
import getCurrentUser from './actions/getCurrentUser'
import './globals.css'
import { Inter } from 'next/font/google'
import { ToastProvider } from '@/providers/toastProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const currenUser = await getCurrentUser()
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastProvider />
        <Navbar currenUser={currenUser} />
        {children}
      </body>
    </html>
  )
}
